deploy:
    - provider: pages # Tell Travis we want to deploy to Github Pages
      skip-cleanup: true
      github-token: $TOKEN # Will take the environment variable you created on step 5
      local_dir: site # The folder that needs to be deployed
      repo: ThomasAndrewMacLean/franky-reis # Add your username/project_name here
      target_branch: gh-pages # Tell Travis to deploy on the gh-pages branch
      on:
          branch: master 